### ISSUE TITLE
Speed Limit Predictor

### ISSUE THREAD

**Issue by Andrealberti** [ProjectoOfficial/ComputerVisionProject#1]
Hello guys,

I was wondering if your speed limit recognition model is available in the repository, I can't find it.

BR,
Andrea

**Comment by ProjectoOfficial** [comment]
You can find speed limits detection and classification at the following link: https://github.com/ProjectoOfficial/ComputerVisionProject/blob/main/traffic/traffic_video.py

or at ComputerVisionProject > traffic > traffic_video.py
The file contains all the necessary utilities to address this task and an example of usage at the bottom of it.
